#include QMK_KEYBOARD_H

#include keymap_swedish.h
#include sendstring_swedish.h


//#define SE_ARNG KC_LBRC // Å
//#define SE_ODIA KC_SCLN // Ö
//#define SE_ADIA KC_QUOT // Ä

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, LGUI_T(KC_Z), LALT_T(KC_X), LCTL_T(KC_C), LSFT_T(KC_V), RCTL_T(KC_B), KC_N, RSFT_T(KC_M), RCTL_T(KC_COMM), LALT_T(KC_DOT), RGUI_T(KC_SLSH), LT(3,KC_TAB), LT(2,KC_SPC), KC_ENT, LT(1,KC_BSPC)),
	[1] = LAYOUT_split_3x5_2(KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_PSCR, KC_SCLN, KC_4, KC_5, KC_6, KC_EQL, KC_CAPS, KC_LEFT, KC_DOWN, KC_RGHT, KC_INS, LGUI_T(KC_GRV), LALT_T(KC_1), LCTL_T(KC_2), LSFT_T(KC_3), KC_BSLS, KC_PGDN, KC_RSFT, RCTL_T(KC_ESC), RALT_T(KC_DEL), KC_RGUI, KC_0, KC_MINS, KC_NO, KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_NO, KC_F7, KC_F8, KC_F9, KC_F12, KC_WH_U, KC_WH_L, KC_MS_U, KC_WH_R, KC_VOLU, KC_ESC, KC_F4, KC_F5, KC_F6, KC_F11, KC_BTN3, KC_MS_L, KC_MS_D, KC_MS_R, KC_VOLD, KC_LGUI, LALT_T(KC_F1), LCTL_T(KC_F2), LSFT_T(KC_F3), KC_F10, KC_WH_D, RSFT_T(KC_MPRV), RCTL_T(KC_MPLY), RALT_T(KC_MNXT), RGUI_T(KC_MUTE), KC_NO, KC_TRNS, KC_BTN2, KC_BTN1),
	[3] = LAYOUT_split_3x5_2(KC_NO, KC_AMPR, KC_ASTR, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_COLN, KC_EQL, KC_UNDS, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_DQUO, LCAG(KC_NO), KC_NO, KC_LEFT, KC_RGHT, KC_NO, KC_NO, CW_TOGG, KC_LPRN, KC_RPRN, KC_SLSH, KC_NO, KC_NO, KC_NO, KC_NO)
};



#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



